[package]
name = "nacos-rust"
version = "0.1.0"
edition = "2021"
authors = ['yaphets andrew']
description = "nacos config in rust."

[workspace]
members = ["nacos-core", "nacos-config-derive", "nacos-common", "nacos-client", "nacos-proto", "nacos-api"]