[package]
name = "nacos-common"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
serde = {version = "1.0.130", features = ["derive", "std"]}
serde_json = "1.0.72"
log = "0.4.14"
anyhow = "1.0.52"